/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAddonsManager,
  IAddonsManagerInterface,
} from "../../../../contracts/interfaces/addons/IAddonsManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "strategy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "kind",
        type: "uint8",
      },
    ],
    name: "RegisterStrategy",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "strategy",
        type: "address",
      },
    ],
    name: "isWhitelistedStrategy",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "strategy",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "kind",
        type: "uint8",
      },
    ],
    name: "registerStrategy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "kind",
        type: "uint8",
      },
    ],
    name: "strategyOfKind",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAddonsManager__factory {
  static readonly abi = _abi;
  static createInterface(): IAddonsManagerInterface {
    return new Interface(_abi) as IAddonsManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAddonsManager {
    return new Contract(address, _abi, runner) as unknown as IAddonsManager;
  }
}
