/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC721Mintable,
  IERC721MintableInterface,
} from "../../../../contracts/interfaces/addons/IERC721Mintable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
    ],
    name: "safeMintBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "tokenUri",
        type: "string",
      },
    ],
    name: "safeMintWithTokenUri",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC721Mintable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721MintableInterface {
    return new Interface(_abi) as IERC721MintableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC721Mintable {
    return new Contract(address, _abi, runner) as unknown as IERC721Mintable;
  }
}
