/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFreeMintWhitelistStrategy,
  IFreeMintWhitelistStrategyInterface,
} from "../../../../contracts/interfaces/addons/IFreeMintWhitelistStrategy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FreeMint",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "merkleRoot",
        type: "bytes32",
      },
    ],
    name: "UpdateMerkleRoot",
    type: "event",
  },
  {
    inputs: [],
    name: "campaignId",
    outputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "leafData",
        type: "bytes",
      },
      {
        internalType: "bytes32[]",
        name: "proof",
        type: "bytes32[]",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "freeMintWhitelist",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "merkleRoot",
        type: "bytes32",
      },
    ],
    name: "updateMerkleRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFreeMintWhitelistStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IFreeMintWhitelistStrategyInterface {
    return new Interface(_abi) as IFreeMintWhitelistStrategyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFreeMintWhitelistStrategy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IFreeMintWhitelistStrategy;
  }
}
