/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Collection1155Base } from "./Collection1155Base";
export type { Collection1155V2 } from "./Collection1155V2";
