/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDynamicV2Interface extends Interface {
  getFunction(
    nameOrSignature: "read" | "write" | "writeBatch"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "WriteBatch"): EventFragment;

  encodeFunctionData(
    functionFragment: "read",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "write",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "writeBatch",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "read", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "write", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "writeBatch", data: BytesLike): Result;
}

export namespace WriteBatchEvent {
  export type InputTuple = [
    collection: AddressLike,
    startId: BigNumberish,
    endId: BigNumberish,
    key: BytesLike,
    value: BytesLike
  ];
  export type OutputTuple = [
    collection: string,
    startId: bigint,
    endId: bigint,
    key: string,
    value: string
  ];
  export interface OutputObject {
    collection: string;
    startId: bigint;
    endId: bigint;
    key: string;
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDynamicV2 extends BaseContract {
  connect(runner?: ContractRunner | null): IDynamicV2;
  waitForDeployment(): Promise<this>;

  interface: IDynamicV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  read: TypedContractMethod<
    [collection: AddressLike, tokenId: BigNumberish, key: BytesLike],
    [string],
    "view"
  >;

  write: TypedContractMethod<
    [
      collection: AddressLike,
      tokenId: BigNumberish,
      key: BytesLike,
      value: BytesLike
    ],
    [void],
    "payable"
  >;

  writeBatch: TypedContractMethod<
    [
      collection: AddressLike,
      startId: BigNumberish,
      endId: BigNumberish,
      key: BytesLike,
      value: BytesLike
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "read"
  ): TypedContractMethod<
    [collection: AddressLike, tokenId: BigNumberish, key: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "write"
  ): TypedContractMethod<
    [
      collection: AddressLike,
      tokenId: BigNumberish,
      key: BytesLike,
      value: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "writeBatch"
  ): TypedContractMethod<
    [
      collection: AddressLike,
      startId: BigNumberish,
      endId: BigNumberish,
      key: BytesLike,
      value: BytesLike
    ],
    [void],
    "payable"
  >;

  getEvent(
    key: "WriteBatch"
  ): TypedContractEvent<
    WriteBatchEvent.InputTuple,
    WriteBatchEvent.OutputTuple,
    WriteBatchEvent.OutputObject
  >;

  filters: {
    "WriteBatch(address,uint256,uint256,bytes32,bytes)": TypedContractEvent<
      WriteBatchEvent.InputTuple,
      WriteBatchEvent.OutputTuple,
      WriteBatchEvent.OutputObject
    >;
    WriteBatch: TypedContractEvent<
      WriteBatchEvent.InputTuple,
      WriteBatchEvent.OutputTuple,
      WriteBatchEvent.OutputObject
    >;
  };
}
