/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IFreeMintCommunityStrategyInterface extends Interface {
  getFunction(
    nameOrSignature: "campaignId" | "claimableAmount" | "freeMint"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FreeMint"): EventFragment;

  encodeFunctionData(
    functionFragment: "campaignId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "freeMint",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "campaignId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "freeMint", data: BytesLike): Result;
}

export namespace FreeMintEvent {
  export type InputTuple = [receiver: AddressLike, amount: BigNumberish];
  export type OutputTuple = [receiver: string, amount: bigint];
  export interface OutputObject {
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IFreeMintCommunityStrategy extends BaseContract {
  connect(runner?: ContractRunner | null): IFreeMintCommunityStrategy;
  waitForDeployment(): Promise<this>;

  interface: IFreeMintCommunityStrategyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  campaignId: TypedContractMethod<[], [string], "view">;

  claimableAmount: TypedContractMethod<
    [receiver: AddressLike],
    [bigint],
    "view"
  >;

  freeMint: TypedContractMethod<[amount: BigNumberish], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "campaignId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimableAmount"
  ): TypedContractMethod<[receiver: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "freeMint"
  ): TypedContractMethod<[amount: BigNumberish], [void], "payable">;

  getEvent(
    key: "FreeMint"
  ): TypedContractEvent<
    FreeMintEvent.InputTuple,
    FreeMintEvent.OutputTuple,
    FreeMintEvent.OutputObject
  >;

  filters: {
    "FreeMint(address,uint256)": TypedContractEvent<
      FreeMintEvent.InputTuple,
      FreeMintEvent.OutputTuple,
      FreeMintEvent.OutputObject
    >;
    FreeMint: TypedContractEvent<
      FreeMintEvent.InputTuple,
      FreeMintEvent.OutputTuple,
      FreeMintEvent.OutputObject
    >;
  };
}
