/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDerivedAccount,
  IDerivedAccountInterface,
} from "../../../contracts/interfaces/IDerivedAccount";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "requestToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RoyaltyClaimed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "requestToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "claimRoyalty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IDerivedAccount__factory {
  static readonly abi = _abi;
  static createInterface(): IDerivedAccountInterface {
    return new Interface(_abi) as IDerivedAccountInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDerivedAccount {
    return new Contract(address, _abi, runner) as unknown as IDerivedAccount;
  }
}
