/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC6551Registry } from "./ERC6551Registry";
export type { IERC6551Registry } from "./IERC6551Registry";
